In [6]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

In [7]:
print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


In [8]:
x = 3
print(x, type(x))

3 <class 'int'>


In [9]:
print(x + 1)   
print(x - 1)   
print(x * 2)   
print(x ** 2) 

4
2
6
9


In [10]:
x += 1
print(x)
x *= 2
print(x)

4
8


In [11]:
y = 2.5
print(type(y))
print(y, y + 1, y * 2, y ** 2)


<class 'float'>
2.5 3.5 5.0 6.25


In [12]:
t, f = True, False
print(type(t))


<class 'bool'>


In [13]:
print(t and f) 
print(t or f)  
print(not t)   
print(t != f)  

False
True
False
True


In [14]:
hello = 'hello'   
world = "world"   
print(hello, len(hello))

hello 5


In [15]:
hw = hello + ' ' + world  
print(hw)


hello world


In [16]:
hw12 = '{} {} {}'.format(hello, world, 12)  
print(hw12)


hello world 12


In [17]:
s = "hello"
print(s.capitalize())  # Capitalize a string
print(s.upper())  
print(s.rjust(7)
print(s.center(7))     
print(s.replace('l', '(ell)'))  
print('  world '.strip())  

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


In [18]:
xs = [3, 1, 2]   
print(xs, xs[2])
print(xs[-1]) 

[3, 1, 2] 2
2


In [19]:
xs[2] = 'foo'    
print(xs)


[3, 1, 'foo']


In [20]:
xs.append('bar') 
print(xs)  

[3, 1, 'foo', 'bar']


In [21]:
x = xs.pop()     
print(x, xs)


bar [3, 1, 'foo']


In [22]:
nums = list(range(5))   
print(nums)         
print(nums[2:4])    
print(nums[2:])     
print(nums[:2])     
print(nums[:])  
print(nums[:-1])    
nums[2:4] = [8, 9] 
print(nums) 

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


In [23]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)


cat
dog
monkey


In [24]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))


#1: cat
#2: dog
#3: monkey


In [25]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)


[0, 1, 4, 9, 16]


In [26]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


In [27]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)


[0, 4, 16]


In [28]:
d = {'cat': 'cute', 'dog': 'furry'}  
print(d['cat'])       
print('cat' in d)

cute
True


In [29]:
d['fish'] = 'wet'    
print(d['fish'])  

wet


In [30]:
print(d['monkey'])  

KeyError: 'monkey'

In [ ]:
print(d.get('monkey', 'N/A'))  
print(d.get('fish', 'N/A'))    


In [31]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A {} has {} legs'.format(animal, legs))


A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [32]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)


{0: 0, 2: 4, 4: 16}


In [33]:
animals = {'cat', 'dog'}

In [34]:
print('cat' in animals)   
print('fish' in animals) 

True
False


In [35]:
animals.add('fish')      
print('fish' in animals)
print(len(animals)) 

True
3


In [36]:
animals.add('cat')       
print(len(animals))       
animals.remove('cat')    
print(len(animals)) 

3
2


In [37]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))

#1: fish
#2: cat
#3: dog


In [38]:
from math import sqrt
print({int(sqrt(x)) for x in range(30)})

{0, 1, 2, 3, 4, 5}


In [39]:
d = {(x, x + 1): x for x in range(10)}  
t = (5, 6)       
print(type(t))
print(d[t])       
print(d[(1, 2)])


<class 'tuple'>
5
1


In [42]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'
for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


In [43]:
def hello(name, loud=False):
    if loud:
        print('HELLO, {}'.format(name.upper()))
    else:
        print('Hello, {}!'.format(name))


In [47]:
 # Constructor
class Greeter:

def __init__(self, name):
    self.name = name  
# Instance method
def greet(self, loud=False):
    if loud:
      print('HELLO, {}'.format(self.name.upper()))
    else:
      print('Hello, {}!'.format(self.name))
g = Greeter('Fred')  
g.greet()            
g.greet(loud=True) 

IndentationError: expected an indented block (<ipython-input-47-850e0ed4d60c>, line 4)

In [48]:
import numpy as np

In [49]:
a = np.array([1, 2, 3]
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 
print(a) 

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [50]:
b = np.array([[1,2,3],[4,5,6]])   
print(b)


[[1 2 3]
 [4 5 6]]


In [51]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [52]:
a = np.zeros((2,2)) 
print(a)

[[0. 0.]
 [0. 0.]]


In [53]:
b = np.ones((1,2))  
print(b)


[[1. 1.]]


In [54]:
c = np.full((2,2), 7) 
print(c)


[[7 7]
 [7 7]]


In [55]:
d = np.eye(2)        
print(d)

[[1. 0.]
 [0. 1.]]


In [56]:
e = np.random.random((2,2)) 

In [57]:
print(e)


[[0.66102928 0.74063732]
 [0.24478496 0.34480806]]


In [58]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [59]:
print(a[0, 1])
b[0, 0] = 77    
print(a[0, 1]) 

2
77


In [60]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [61]:
row_r1 = a[1, :]
row_r2 = a[1:2, :]  
row_r3 = a[[1], :]  
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [62]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)


[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [63]:
a = np.array([[1,2], [3, 4], [5, 6]]
print(a[[0, 1, 2], [0, 1, 0]])

print(np.array([a[0, 0], a[1, 1], a[2, 0]]))


[1 4 5]
[1 4 5]


In [64]:
print(a[[0, 0], [1, 1]])

[2 2]


In [65]:
print(np.array([a[0, 1], a[0, 1]]))


[2 2]


In [66]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [67]:
s
b = np.array([0, 2, 0, 1])

In [68]:
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [69]:
a[np.arange(4), b] += 10
print(a)


[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [70]:
a = np.array([[1,2], [3, 4], [5, 6]])


In [71]:
bool_idx = (a > 2)  
                
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [72]:
print(a[bool_idx]
print(a[a > 2])


[3 4 5 6]
[3 4 5 6]


In [73]:
x = np.array([1, 2])  
y = np.array([1.0, 2.0])  
z = np.array([1, 2], dtype=np.int64)  
print(x.dtype, y.dtype, z.dtype)


int32 float64 int64


In [74]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [75]:
print(x - y)
print(np.subtract(x, y))


[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [76]:
print(x * y)
print(np.multiply(x, y))


[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [77]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [78]:
print(np.sqrt(x))


[[1.         1.41421356]
 [1.73205081 2.        ]]


In [79]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])


In [80]:
print(v.dot(w))
print(np.dot(v, w))


219
219


In [81]:
print(v @ w)

219


In [82]:
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)


[29 67]
[29 67]
[29 67]


In [83]:
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [84]:
x = np.array([[1,2],[3,4]])
print(np.sum(x))  
print(np.sum(x, axis=0))  
print(np.sum(x, axis=1))  

10
[4 6]
[3 7]


In [85]:
print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]


In [86]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)


[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


In [87]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [88]:
vv = np.tile(v, (4, 1)) 
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [89]:
y = x + vv  
print(y)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [90]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  
print(y)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
